### ISSUE TITLE
got an unexpected keyword argument 'trainable_orientation'

### ISSUE THREAD

**Issue by LouisChowX** [NVlabs/diff-rt#5]
hi, l meet a problem while running learning_orientation.ipynb in jupyter notebook. Here is the problem:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_34764\3417808883.py in <module>
     24 
     25 # Create a transmitter and add it to the scene
---> 26 tx = Transmitter("tx", position=[-232, 130, 25.0],
     27                  orientation=[0.0,0.0,0.0],
     28                  trainable_orientation=True) # Trainable orientation

TypeError: __init__() got an unexpected keyword argument 'trainable_orientation'

My platform is windows and the versions:
 sionna: 0.16.2
tensorflow: 2.10.1
python:3.9.13

I did not change any code from the code you provide. Do you have any idea how to solve it?
Thank you!

**Comment by jhoydis** [comment]
Hi, 

Could you try to downgrade to Sionna v0.15? We removed the `trainable_orientation` flag in v0.16 (see [release notes](https://github.com/NVlabs/sionna/discussions/274)). 

Otherwise you could try to replace this code
```
# Create a transmitter and add it to the scene
tx = Transmitter("tx", position=[-232, 130, 25.0],
                 orientation=[0.0,0.0,0.0],
                 trainable_orientation=True) # Trainable orientation
```
by
```
tx = Transmitter("tx", position=[-232, 130, 25.0],
                 orientation=tf.Variable([0.0,0.0,0.0])) # Trainable orientation
```

We will also update the notebooks for compatibility soon.

**Comment by LouisChowX** [comment]
Thank you very much for your suggestions! 
The first suggestion, downgrading Sionna to v0.15, it did work!
However, it seems the variables are not updated correctly by the second solution. It ends up to print the following message at each step:

Training step 29 - Rate: NaN bit - tx orientation: [NaN   NaN  NaN]

Anyway, my problem is solved and the orientation can be trained normally.
I hope my experiment with regard to the two solutions will help more people.

Best wishes

**Comment by jhoydis** [comment]
I can reproduce the NaN error. This should not happen. Will look into it.

**Comment by jhoydis** [comment]
It seems to come from Sionna v0.16.2. With v0.16.1 it works just fine.

**Comment by LouisChowX** [comment]
Yes, I agree. Thank you for your reply and I think our conversations will also help others a lot!
